
#! /bin/bash

export HGCALL1IMAGES=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)
export DEEPJETCORE_SUBPACKAGE=$HGCALL1IMAGES

cd $HGCALL1IMAGES
export PYTHONPATH=$HGCALL1IMAGES/modules:$PYTHONPATH
export PYTHONPATH=$HGCALL1IMAGES/modules/datastructures:$PYTHONPATH
export PATH=$HGCALL1IMAGES/scripts:$PATH

export LD_LIBRARY_PATH=$HGCALL1IMAGES/modules/compiled:$LD_LIBRARY_PATH
export PYTHONPATH=$HGCALL1IMAGES/modules/compiled:$PYTHONPATH

